# hop release: 0.0.2
# pylint: disable=wrong-import-order, invalid-name, attribute-defined-outside-init

"""The module halftest.blog.view.post_comment povides the PostComment class.

WARNING!

This file is part of the halftest package. It has been generated by the
command hop. To keep it in sync with your database structure, just rerun
hop update.

More information on the half_orm library on https://github.com/collorg/halfORM.

DO NOT REMOVE OR MODIFY THE LINES BEGINING WITH:
#>>> PLACE YOUR CODE BELOW...
#<<< PLACE YOUR CODE ABOVE...

MAKE SURE YOUR CODE GOES BETWEEN THESE LINES OR AT THE END OF THE FILE.
hop ONLY PRESERVES THE CODE BETWEEN THESE MARKS WHEN IT IS RUN.


"""

from halftest.db_connector import base_relation_class

#>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!

#<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!

__RCLS = base_relation_class('blog.view.post_comment')

class PostComment(__RCLS):
    """
    __RCLS: <class 'half_orm.relation.View_HalftestBlogviewPost_comment'>
    This class allows you to manipulate the data in the PG relation:
    VIEW: "halftest"."blog.view"."post_comment"
    DESCRIPTION:
    This view joins:
    - comment,
    - author of the comment,
    - post,
    - author of the post.
    FIELDS:
    - post_title:                (text)
    - author_post_id:            (int4)
    - author_post_first_name:    (text)
    - author_post_last_name:     (text)
    - comment_id:                (int4)
    - comment_content:           (text)
    - post_id:                   (int4)
    - author_comment_id:         (int4)
    - author_comment_first_name: (text)
    - author_comment_last_name:  (text)
    """
    #>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!

    #<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        #>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
