image: python:${PYVERSION}-bullseye

stages:
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  HALFORM_CONF_DIR: "$CI_PROJECT_DIR/.config"
  GIT_STRATEGY: clone

.before_script_template: &test
  before_script:
    - apt-get update
    - apt-get install -y postgresql tree
    - service postgresql start
    - su - postgres -c "psql template1 -c \"create user halftest with password 'halftest';\" "
    - su - postgres -c "psql template1 -c 'ALTER USER halftest WITH SUPERUSER'"
    - su - postgres -c "psql template1 -c \"create user root with password 'root';\" "
    - su - postgres -c "psql template1 -c 'ALTER USER root WITH SUPERUSER'"
    - su - postgres -c "createdb halftest -O halftest"
    - su - postgres -c "createdb hop_test -O halftest"
    - su - postgres -c "psql halftest -f $CI_PROJECT_DIR/test/sql/halftest.sql"
    - /usr/local/bin/python -m pip install --upgrade pip
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install .
    - pip install pytest
    - useradd halftest

.before_script_template: &build
  before_script:
    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip install .
    - pip install build

test:
  stage: test
  <<: *test
  parallel:
    matrix:
      - PYVERSION: ["3.6", "3.7", "3.8", "3.9", "3.10", "3.11"]
  script:
    - pytest
    - "$CI_PROJECT_DIR/half_orm/packager/test/dummy_test.sh"

build:
  stage: build
  <<: *build
  parallel:
    matrix:
      - PYVERSION: ["3.11"]
  script:
    python -m build
  artifacts:
    paths:
      - "$CI_PROJECT_DIR/dist"
    expire_in: 1 week
