import psycopg
import typing
import datetime
import uuid

__SQL_ADAPTER = {
  'string': (str, None),
  'bigint': (int, None),
  'int8': (int, None),
  'bigserial': (int, None),
  'serial8': (int, None),
  'boolean': (bool, None),
  'bool': (bool, None),
  'character': (str, None),
  'char': (str, None),
  'bpchar': (str, None),
  'character varying': (str, None),
  'varchar': (str, None),
  'cidr': (typing.Any, None),
  'circle': (typing.Any, None),
  'date': (datetime.date, None),
  'double precision': (float, None),
  'float8': (float, None),
  'inet': (typing.Any, None),
  'integer': (int, None),
  'int': (int, None),
  'int4': (int, None),
  'interval': (typing.Any, None),
  'json': (typing.Any, psycopg.types.json.Json),
  'jsonb': (typing.Any, psycopg.types.json.Jsonb),
  'line': (typing.Any, None),
  'lseg': (typing.Any, None),
  'macaddr': (typing.Any, None),
  'macaddr8': (typing.Any, None),
  'money': (typing.Any, None),
  'numeric': (float, None),
  'decimal': (float, None),
  'path': (str, None),
  'pg_lsn': (typing.Any, None),
  'pg_snapshot': (typing.Any, None),
  'point': (typing.Any, None),
  'polygon': (typing.Any, None),
  'real': (float, None),
  'float4': (float, None),
  'smallint': (int, None),
  'int2': (int, None),
  'smallserial': (int, None),
  'serial2': (int, None),
  'serial': (int, None),
  'serial4': (int, None),
  'text': (str, None),
  'time': (datetime.datetime, None),
  'timestamp': (datetime.datetime, None),
  'tsquery': (typing.Any, None),
  'tsvector': (typing.Any, None),
  'txid_snapshot': (typing.Any, None),
  'uuid': (uuid.UUID, None),
  'xml': (typing.Any, None),
}

__SQL_ADAPTER.update({f'_{key}': value for key, value in __SQL_ADAPTER.items()})
SQL_ADAPTER = __SQL_ADAPTER