#-*- coding: utf-8 -*-
# pylint: disable=wrong-import-order

"""The module halftest.blog.comment povides the Comment class.

WARNING!

This file is part of the halftest package. It has been generated by the
command halfORM. To keep it in sync with your database structure, just rerun
halfORM.

More information on the half_orm library on https://github.com/collorg/halfORM.


DO NOT REMOVE OR MODIFY THE LINES BEGINING WITH:
#>>> PLACE YOUR CODE BELOW...
#<<< PLACE YOUR CODE ABOVE...

MAKE SURE YOU PLACE YOUR CODE BETWEEN THESE LINES OR AT THE END OF THE FILE.
halfORM ONLY PRESERVES THE CODE BETWEEN THESE MARKS WHEN IT IS RUN.
"""

from halftest.db_connector import base_relation_class

#>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
FKEYS_PROPERTIES = [
    ('post_', 'post'),
    ('author_', 'author')
]
#<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!

__RCLS = base_relation_class('blog.comment')

class Comment( __RCLS):
    """
    __RCLS: <class 'half_orm.relation.Table_HalftestBlogComment'>
    This class allows you to manipulate the data in the PG relation:
    TABLE: "halftest"."blog"."comment"
    DESCRIPTION:
    The table blog.comment contains all the comments
    made by a person on a post.
    FIELDS:
    - id:        (int4) PK
    - content:   (text)
    - post_id:   (int4)
    - author_id: (int4)
    FOREIGN KEYS:
    - post: (post_id)
     ↳ "halftest"."blog"."post"(id)
    - author: (author_id)
     ↳ "halftest"."actor"."person"(id)
    """
    def __init__(self, **kwargs):
        super(Comment, self).__init__(**kwargs)

        #>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
