#-*- coding: utf-8 -*-
# pylint: disable=wrong-import-order

"""The module halftest.blog.event povides the Event class.

WARNING!

This file is part of the halftest package. It has been generated by the
command halfORM. To keep it in sync with your database structure, just rerun
halfORM.

More information on the half_orm library on https://github.com/collorg/halfORM.


DO NOT REMOVE OR MODIFY THE LINES BEGINING WITH:
#>>> PLACE YOUR CODE BELOW...
#<<< PLACE YOUR CODE ABOVE...

MAKE SURE YOU PLACE YOUR CODE BETWEEN THESE LINES OR AT THE END OF THE FILE.
halfORM ONLY PRESERVES THE CODE BETWEEN THESE MARKS WHEN IT IS RUN.
"""

from halftest.db_connector import base_relation_class
from halftest.blog.post import Post as BlogPost
#>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
FKEYS_PROPERTIES = [
    ('fk_author', 'author'),
    ('comment_fk', '_reverse_fkey_halftest_blog_comment_post_id')
]
#<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!

__RCLS = base_relation_class('blog.event')

class Event(BlogPost, __RCLS):
    """
    __RCLS: <class 'half_orm.relation.Table_HalftestBlogEvent'>
    This class allows you to manipulate the data in the PG relation:
    TABLE: "halftest"."blog"."event"
    DESCRIPTION:
    The table blog.event contains all the events
    of the blogging system. It inherits blog.post.
    It's just here to illustrate the inheriance in half_orm
    FIELDS:
    - id:                (int4) PK
    - title:             (text)
    - content:           (text)
    - author_first_name: (text)
    - author_last_name:  (text)
    - author_birth_date: (date)
    - begin:             (timestamp)
    - end:               (timestamp)
    - location:          (text)
    FOREIGN KEYS:
    - author: (author_first_name, author_last_name, author_birth_date)
     ↳ "halftest"."actor"."person"(first_name, last_name, birth_date)
    - _reverse_fkey_halftest_blog_comment_post_id: (id)
     ↳ "halftest"."blog"."comment"(post_id)
    """
    def __init__(self, **kwargs):
        super(Event, self).__init__(**kwargs)

        #>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
