# pylint: disable=wrong-import-order, invalid-name, attribute-defined-outside-init

"""The module halftest.blog.post povides the Post class.

WARNING!

This file is part of the halftest package. It has been generated by the
command hop. To keep it in sync with your database structure, just rerun
hop update.

More information on the half_orm library on https://github.com/collorg/halfORM.

DO NOT REMOVE OR MODIFY THE LINES BEGINING WITH:
#>>> PLACE YOUR CODE BELOW...
#<<< PLACE YOUR CODE ABOVE...

MAKE SURE YOUR CODE GOES BETWEEN THESE LINES OR AT THE END OF THE FILE.
hop ONLY PRESERVES THE CODE BETWEEN THESE MARKS WHEN IT IS RUN.
"""

from halftest import base_relation_class

#>>> PLACE YOUR CODE BELOW THIS LINE. DO NOT REMOVE THIS LINE!

#<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!

__RCLS = base_relation_class('blog.post')

class Post(__RCLS):
    """
    __RCLS: <class 'half_orm.relation_factory.Table_HalftestBlogPost'>
    This class allows you to manipulate the data in the PG relation:
    TABLE: "halftest":"blog"."post"
    DESCRIPTION:
    The table blog.post contains all the post
    made by a person in the blogging system.
    FIELDS:
    - id:                (int4) NOT NULL
    - title:             (text)
    - content:           (text)
    - author_first_name: (text)
    - author_last_name:  (text)
    - author_birth_date: (date)
    - data:              (jsonb)

    PRIMARY KEY (id)
    UNIQUE CONSTRAINT (title, content)
    FOREIGN KEYS:
    - _reverse_fkey_halftest_blog_comment_post_id: ("id")
     ↳ "halftest":"blog"."comment"(post_id)
    - author: ("author_birth_date", "author_first_name", "author_last_name")
     ↳ "halftest":"actor"."person"(first_name, last_name, birth_date)

    To use the foreign keys as direct attributes of the class, copy/paste the Fkeys below into
    your code as a class attribute and replace the empty string key(s) with the alias(es) you
    want to use. The aliases must be unique and different from any of the column names. Empty
    string keys are ignored.

    Fkeys = {
        '': '_reverse_fkey_halftest_blog_comment_post_id',
        '': 'author',
    }
    """
    #>>> PLACE YOUR CODE BELOW THIS LINE. DO NOT REMOVE THIS LINE!
    Fkeys = {
        'comment_rfk': '_reverse_fkey_halftest_blog_comment_post_id',
        'author_fk': 'author',
    }

    #<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        #>>> PLACE YOUR CODE BELOW THIS LINE. DO NOT REMOVE THIS LINE!
