#-*- coding: utf-8 -*-
# pylint: disable=wrong-import-order

"""The module halftest.blog.post povides the Post class.

WARNING!

This file is part of the halftest package. It has been generated by the
command halfORM. To keep it in sync with your database structure, just rerun
halfORM.

More information on the half_orm library on https://github.com/collorg/halfORM.


DO NOT REMOVE OR MODIFY THE LINES BEGINING WITH:
#>>> PLACE YOUR CODE BELOW...
#<<< PLACE YOUR CODE ABOVE...

MAKE SURE YOU PLACE YOUR CODE BETWEEN THESE LINES OR AT THE END OF THE FILE.
halfORM ONLY PRESERVES THE CODE BETWEEN THESE MARKS WHEN IT IS RUN.
"""

from halftest.db_connector import base_relation_class

#>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
FKEYS = [
    ('author_', 'author'),
    ('comment_fk', '_reverse_fkey_halftest_blog_comment_post_id')
]
#<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!

__RCLS = base_relation_class('blog.post')

class Post( __RCLS):
    """
    __RCLS: <class 'half_orm.relation.Table_HalftestBlogPost'>
    This class allows you to manipulate the data in the PG relation:
    TABLE: "halftest"."blog"."post"
    DESCRIPTION:
    The table blog.post contains all the post
    made by a person in the blogging system.
    FIELDS:
    - id:                (int4) PK
    - title:             (text)
    - content:           (text)
    - author_first_name: (text)
    - author_last_name:  (text)
    - author_birth_date: (date)
    FOREIGN KEYS:
    - _reverse_fkey_halftest_blog_comment_post_id: (id)
     ↳ "halftest"."blog"."comment"(post_id)
    - author: (author_first_name, author_last_name, author_birth_date)
     ↳ "halftest"."actor"."person"(first_name, last_name, birth_date)
    """
    def __init__(self, **kwargs):
        super(Post, self).__init__(**kwargs)

        #>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
