#-*- coding: utf-8 -*-
# pylint: disable=wrong-import-order

"""The module halftest.actor.person povides the Person class.

WARNING!

This file is part of the halftest package. It has been generated by the
command halfORM. To keep it in sync with your database structure, just rerun
halfORM.

More information on the half_orm library on https://github.com/collorg/halfORM.


DO NOT REMOVE OR MODIFY THE LINES BEGINING WITH:
#>>> PLACE YOUR CODE BELOW...
#<<< PLACE YOUR CODE ABOVE...

MAKE SURE YOU PLACE YOUR CODE BETWEEN THESE LINES OR AT THE END OF THE FILE.
halfORM ONLY PRESERVES THE CODE BETWEEN THESE MARKS WHEN IT IS RUN.
"""

from halftest.db_connector import base_relation_class

#>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
FKEYS = [
    ('_comment', '_reverse_fkey_halftest_blog_comment_author_id'),
    ('_event', '_reverse_fkey_halftest_blog_event_author_first_name_author_last_name_author_birth_date'),
    ('_post', '_reverse_fkey_halftest_blog_post_author_first_name_author_last_name_author_birth_date')
]
#<<< PLACE YOUR CODE ABOVE THIS LINE. DO NOT REMOVE THIS LINE!

__RCLS = base_relation_class('actor.person')

class Person( __RCLS):
    """
    __RCLS: <class 'half_orm.relation.Table_HalftestActorPerson'>
    This class allows you to manipulate the data in the PG relation:
    TABLE: "halftest"."actor"."person"
    DESCRIPTION:
    The table actor.person contains the persons of the blogging system.
    The id attribute is a serial. Just pass first_name, last_name and birth_date
    to insert a new person.
    FIELDS:
    - id:         (int4) UNIQUE NOT NULL
    - first_name: (text) PK
    - last_name:  (text) PK
    - birth_date: (date) PK
    FOREIGN KEYS:
    - _reverse_fkey_halftest_blog_comment_author_id: (id)
     ↳ "halftest"."blog"."comment"(author_id)
    - _reverse_fkey_halftest_blog_event_author_first_name_author_last_name_author_birth_date: (first_name, last_name, birth_date)
     ↳ "halftest"."blog"."event"(author_first_name, author_last_name, author_birth_date)
    - _reverse_fkey_halftest_blog_post_author_first_name_author_last_name_author_birth_date: (first_name, last_name, birth_date)
     ↳ "halftest"."blog"."post"(author_first_name, author_last_name, author_birth_date)
    """
    def __init__(self, **kwargs):
        super(Person, self).__init__(**kwargs)

        #>>> PLACE YOUR CODE BELLOW THIS LINE. DO NOT REMOVE THIS LINE!
