# .github/ISSUE_TEMPLATE/extension_request.yml
name: 🔌 Extension Request
description: Request a new official halfORM extension
title: "[Extension] "
labels: ["extension", "enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an extension idea!
        
        Official extensions are maintained by the halfORM team and follow strict quality guidelines.

  - type: input
    id: name
    attributes:
      label: Extension Name
      description: Proposed name for the extension
      placeholder: "half-orm-my-extension"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: What would this extension do?
      placeholder: "This extension would provide..."
    validations:
      required: true

  - type: textarea
    id: commands
    attributes:
      label: CLI Commands
      description: What commands would this extension add?
      placeholder: |
        - half_orm my-extension init
        - half_orm my-extension generate
        - half_orm my-extension deploy

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: When would developers use this extension?
      placeholder: "Developers would use this when..."

  - type: textarea
    id: integration
    attributes:
      label: halfORM Integration
      description: How would this integrate with halfORM core?
      placeholder: "This would work with halfORM by..."

  - type: dropdown
    id: priority
    attributes:
      label: Community Priority
      description: How important do you think this extension is?
      options:
        - Low - Niche use case
        - Medium - Would help many users
        - High - Essential for halfORM ecosystem
        - Critical - Blocking adoption

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution Willingness
      description: Are you willing to contribute to this extension?
      options:
        - label: I'm willing to help develop this extension
        - label: I'm willing to help test this extension
        - label: I'm willing to help write documentation
        - label: I'm willing to help maintain this extension
