# .github/ISSUE_TEMPLATE/feature_request.yml
name: ✨ Feature Request
description: Suggest a new feature for halfORM
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! 
        
        **Before submitting**, please search existing issues to avoid duplicates.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of halfORM would this feature affect?
      options:
        - halfORM Core (ORM functionality)
        - halfORM CLI (command-line interface)
        - halfORM Extensions (extension system)
        - Documentation
        - Tutorial/Examples
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: "I'm frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: usage
    attributes:
      label: Usage Example
      description: Show how this feature would be used
      render: python
      placeholder: |
        # Example usage
        from half_orm.model import Model
        
        # Your proposed API here

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions you've considered?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow
        - High - Blocking current work
        - Critical - Cannot work without it

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to contribute to this feature?
      options:
        - label: I'm willing to submit a PR for this feature
        - label: I'm willing to help test this feature
        - label: I'm willing to help write documentation
